# Site info
title: Cultural Evolution of Texts
name: CEoT
description: Website of the project

# Configutations
theme: jekyll-theme-minimal
show_downloads: false

# Build settings
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    highlighter: rouge
    toc_levels: "1,2,3"
permalink: pretty

# Jekyll
plugins:
    - rouge
    - jemoji


